//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example_Novator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID_Employee { get; set; }
        public string Second_Name { get; set; }
        public string First_Name { get; set; }
        public string Patr_Name { get; set; }
    }
}
